# .github/workflows/main.yml
# github actions
# docker run -e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd` --rm -it takigama/platformio platformio run

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker://takigama/platformio:latest
        with:
          args: platformio run
          options: "-e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd`"
      - name: Archive firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/mkr_wifi1010/firmware.bin
