# .github/workflows/main.yml
# github actions
# docker run -e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd` --rm -it takigama/platformio platformio run

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            # ~/.platformio/.cache
            ~/.platformio
            ~/.pio
          key: ${{ runner.os }}-pio
      #- uses: actions/setup-python@v5
      #  with:
      #    python-version: "3.11"
      #- name: Install PlatformIO Core
      #  run: pip install --upgrade platformio

      - uses: docker://takigama/platformio:latest
        with:
          args: platformio run
          options: "-e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd`"
      - name: Archive firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/mkr_wifi1010/firmware.bin
