# .github/workflows/main.yml
# github actions
# See: https://github.com/takigama/platformio-docker
# docker run -e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd` --rm -it takigama/platformio platformio run
# Further info:
# https://github.com/sglahn/docker-platformio-core
# https://github.com/platformio/platformio-docs/blob/develop/integration/ci/github-actions.rst

name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v4
        with:
          path: |
            .platformio
            # .pio
          key: ${{ runner.os }}-pio
      #- uses: actions/setup-python@v5
      #  with:
      #    python-version: "3.11"
      #- name: Install PlatformIO Core
      #  run: pip install --upgrade platformio

      #- uses: docker://takigama/platformio:latest
      #- name: Log in to the Container registry
      #  uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      #  with:
      #    registry: ghcr.io
      #    username: pbrier
      #    password: ${{ secrets.GITHUB_TOKEN }}   
      #- uses: docker://takigama/platformio:latest
      - uses: docker://ghcr.io/pbrier/platformio:latest
        with:
          args: platformio run
          #options: "-e HOME=`pwd` -u $UID -w `pwd` -v `pwd`:`pwd`"
          options: "-e HOME=`pwd` -w `pwd` -v `pwd`:`pwd`"

      - name: Archive firmware artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/mkr_wifi1010/firmware.bin
